title: "天通辞典"
description: "天通が運用する公開資料網"
lang: ja
url: "https://manzyuball.github.io"
baseurl: "/Tenzu.jp"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - README.md
  - nanboku_nihon_senki.md
